### ISSUE TITLE
Arasan 21 win64 POPCNT time forfeits - ChessGUI 40/2 round robin

### ISSUE THREAD

**Issue by yellow-panther** [jdart1/arasan-chess#19]
Hello Jon,
cf. game 7, 12, 23, 24, 32, 35, 36, 59, 60
[DEBUG.zip](https://github.com/jdart1/arasan-chess/files/2385510/DEBUG.zip)
[OUTPUT.zip](https://github.com/jdart1/arasan-chess/files/2385511/OUTPUT.zip)
[TOURNAMENTS.zip](https://github.com/jdart1/arasan-chess/files/2385512/TOURNAMENTS.zip)

**Comment by jdart1** [comment]
Did this tournament have ponder enabled? There are some known issues with ponder on, fixed in the current master branch.

**Comment by yellow-panther** [comment]
round robin with alternate colours, but the option ponder was disabled.

**Comment by jdart1** [comment]
This looks to me like a problem with lag. In game 7 for example for the last move Arasan has 2594 milliseconds left. The last info line indicates it spent 880 milliseconds in the search and then it generates a bestmove. However, the debug log says "Eng01 (arasanx-64-popcnt) thought for 2715 milliseconds." It also indicates "System time lag per move = 1578 milliseconds". I am a little unclear about this because 1578+880 is less than 2715. But in any case, the lag is significant. The dev version has a Move overhead parameter that can be used to alleviate problems with lag. This will be in the next release (21.1), due pretty soon.

**Comment by jdart1** [comment]
Please try the new Move overhead option and see if setting an appropriate value for that alleviates the issue. Closing this for now but please re-open if it is still an issue.
