### ISSUE TITLE
Change option name SyzygyTbPath to SyzygyPath

### ISSUE THREAD

**Issue by nguyenpham** [jdart1/arasan-chess#26]
Surely it is not a problem, Arasan chess has been working well on my computer.

Just a small suggestion, from a user view (exactly it is a view of a chess interface developer). For engine tournaments, users usually want all engines to use similar cores, memory and give them all common data they want such as Syzygy path. However, configuring tens of engines is not a fun job. If the user does something wrong or changes idea later, he has to redo. Some chess interface (e.g. mine, Banksia) can help users to auto-configure/setup all engines for common options such as the number of cores/threads, memory/threads as well as Syzygy path. To do that, it simply matches names of options to a special list. Banksia doesn't have any problem to auto-setup threads/hash for Arasan chess but Syzygy path since it is different from ones of other engines.

I know naming for options (or whatever) is based on the need and also a primitive rights/freedom of programmers. Furthermore, there are no compulsory names for options in UCI document. However, in UCI document, they have mentioned to some common options' names such as Ponder, Hash, Threads and SyzygyPath. Thus SyzygyPath becomes a kind of "half" standard one.

If you don't want to change, just ignore this post. I will manage to make Banksia to auto-setup for Arasan chess as a special case. If you change, it is good for all of us (including other chess interfaces) in long term even some your current users may get a bit annoyed.

Thanks

**Comment by MichaelB7** [comment]
Hi Jon, @nguyenpham makes a good point.  Also, I know Arasan's genesis is there old winboard style engine (after the standalone GUI/Interfsace), but these days almost everyone today is UCI - so here , I'm a user with over 20 years experience and i if  load as engine as a UCI engine , I'm fat and happy and not checking anything else and start running matches.  I had never realized that current Arasan was not accepting the semi-standard SyzygyPath option since xBoard config says it was loaded asa UCI engine
```
"/Users/michaelb7/cluster.mfb/arasanx" -fd "/Users/michaelb7/cluster.mfb" -fUCI
```
 If I'm doing this , I'm sure there are others as well and , not that it matters to any of us,  but it is probably running at a disadvantage in a fair amount of tournaments and  is not getting the credit (Elo points) it deserves for the effort you have put into it.
Regards,

**Comment by jdart1** [comment]
@nguyenpham, UCI predates Syzygy tablebases, so I don't know from what document you are getting SyzygyPath as a standard. Like other UCI engines, Arasan announces its configuration options on startup and these will be shown in UIs.
